name: Code Quality Checks

on:
  pull_request:
    branches:
      - checkstyle_pmd

jobs:
  code-quality:
    name: Run Checkstyle and PMD
    runs-on: ubuntu-latest

    env:
      WORKING_DIR: helloworld

    steps:
      # Step 1: Checkout code
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Step 2: Verify project files
      - name: Verify Files
        run: ls -la $WORKING_DIR

      # Step 3: Set up Java
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: 'temurin'

      # Step 4: Run Checkstyle
      - name: Run Checkstyle
        run: mvn checkstyle:check -Dcheckstyle.config.location=google_checks.xml
        working-directory: ${{ env.WORKING_DIR }}

      # Step 5: Run PMD
      - name: Run PMD
        run: mvn pmd:check -Dpmd.rulesetfiles=https://raw.githubusercontent.com/pmd/pmd/main/pmd-java/src/main/resources/rulesets/java/quickstart.xml
        working-directory: ${{ env.WORKING_DIR }}
